#!/usr/bin/env python3
"""Audit whether V1 option-value labels are learnable from legal state features.

This is an offline gate. It never submits to Kaggle and never uses opponent identity,
seed, seat, rating, EpisodeId, hidden state or future state as model inputs.

Input: TRAINING_ROWS.jsonl generated by tools/option_value_dataset_ryzen_v1.py
Output: JSON diagnostics + a compact stdout summary.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from collections import defaultdict
from pathlib import Path
from statistics import mean, pstdev

import numpy as np

FORBIDDEN_FEATURE_TOKENS = (
    "seed", "opponent", "rating", "episode", "hidden", "future", "submission",
)
LAMBDA_GRID = (0.01, 0.1, 1.0, 10.0, 100.0)
THRESHOLD_GRID = (-0.05, 0.0, 0.025, 0.05, 0.10, 0.15, 0.20)


def stable_bucket(text: str, modulo: int = 10) -> int:
    h = hashlib.sha256(text.encode("utf-8")).digest()
    return int.from_bytes(h[:8], "big") % modulo


def feature_vector(row: dict, feature_names: list[str]) -> np.ndarray:
    f = row["features"]
    if list(f.keys()) != feature_names:
        raise ValueError("feature order/contract mismatch")
    vals = np.asarray([float(f[k]) for k in feature_names], dtype=np.float64)
    if not np.all(np.isfinite(vals)):
        raise ValueError("non-finite feature")
    return vals


def sign_class(y: float) -> int:
    return 1 if y > 0 else (-1 if y < 0 else 0)


def summarize_rows(rows: list[dict]) -> dict:
    ys = [float(r["score_delta"]) for r in rows]
    ms = [float(r["margin_delta"]) for r in rows]
    return {
        "rows": len(rows),
        "mean_score_delta": mean(ys) if ys else None,
        "mean_margin_delta": mean(ms) if ms else None,
        "positive": sum(y > 0 for y in ys),
        "negative": sum(y < 0 for y in ys),
        "neutral": sum(y == 0 for y in ys),
    }


def fit_ridge(X: np.ndarray, y: np.ndarray, lam: float):
    mu = X.mean(axis=0)
    sd = X.std(axis=0)
    sd = np.where(sd < 1e-12, 1.0, sd)
    Z = (X - mu) / sd
    # Keep explicit bias feature in X if present; numerical ridge is enough.
    A = Z.T @ Z + float(lam) * np.eye(Z.shape[1], dtype=np.float64)
    b = Z.T @ y
    w = np.linalg.solve(A, b)
    intercept = float(y.mean() - ((mu - mu) / sd) @ w)
    return {"mu": mu, "sd": sd, "w": w, "intercept": intercept}


def predict(model, X: np.ndarray) -> np.ndarray:
    Z = (X - model["mu"]) / model["sd"]
    return Z @ model["w"] + model["intercept"]


def metrics(y: np.ndarray, p: np.ndarray, threshold: float) -> dict:
    fire = p > float(threshold)
    realized = y * fire.astype(np.float64)
    nonzero = y != 0.0
    sign_acc = None
    if np.any(nonzero):
        sign_acc = float(np.mean(np.sign(p[nonzero]) == np.sign(y[nonzero])))
    return {
        "rows": int(len(y)),
        "mse": float(np.mean((p - y) ** 2)) if len(y) else None,
        "mae": float(np.mean(np.abs(p - y))) if len(y) else None,
        "threshold": float(threshold),
        "fire_rate": float(np.mean(fire)) if len(y) else None,
        "realized_selector_delta": float(np.mean(realized)) if len(y) else None,
        "always_fire_delta": float(np.mean(y)) if len(y) else None,
        "oracle_row_delta": float(np.mean(np.maximum(y, 0.0))) if len(y) else None,
        "negative_fires": int(np.sum((y < 0) & fire)),
        "positive_captures": int(np.sum((y > 0) & fire)),
        "positive_total": int(np.sum(y > 0)),
        "negative_total": int(np.sum(y < 0)),
        "nonzero_sign_accuracy": sign_acc,
    }


def prepare(rows: list[dict], feature_names: list[str]):
    X = np.vstack([feature_vector(r, feature_names) for r in rows])
    y = np.asarray([float(r["score_delta"]) for r in rows], dtype=np.float64)
    return X, y


def train_dev_test(rows: list[dict], feature_names: list[str]) -> dict:
    # Group split by exact legal state + option. Same state never crosses splits.
    splits = {"train": [], "dev": [], "test": []}
    for r in rows:
        key = f"{r['state_hash']}|{r['option_id']}"
        b = stable_bucket(key, 10)
        target = "train" if b < 6 else ("dev" if b < 8 else "test")
        splits[target].append(r)

    if min(len(v) for v in splits.values()) == 0:
        raise RuntimeError(f"empty grouped split: {{k:len(v) for k,v in splits.items()}}")

    Xtr, ytr = prepare(splits["train"], feature_names)
    Xdv, ydv = prepare(splits["dev"], feature_names)
    Xte, yte = prepare(splits["test"], feature_names)

    candidates = []
    models = {}
    for lam in LAMBDA_GRID:
        model = fit_ridge(Xtr, ytr, lam)
        models[lam] = model
        pdv = predict(model, Xdv)
        for threshold in THRESHOLD_GRID:
            m = metrics(ydv, pdv, threshold)
            candidates.append({
                "lambda": lam,
                "threshold": threshold,
                **m,
            })

    # Maximize realized dev delta, then fewer negative fires, then lower fire rate.
    best = sorted(
        candidates,
        key=lambda x: (
            -float(x["realized_selector_delta"]),
            x["negative_fires"],
            x["fire_rate"] if x["fire_rate"] is not None else 1.0,
            x["lambda"],
            x["threshold"],
        ),
    )[0]
    model = models[best["lambda"]]
    ptr = predict(model, Xtr)
    pdv = predict(model, Xdv)
    pte = predict(model, Xte)

    return {
        "split_rows": {k: len(v) for k, v in splits.items()},
        "selection": {
            "lambda": best["lambda"],
            "threshold": best["threshold"],
            "dev_realized_selector_delta": best["realized_selector_delta"],
        },
        "train": metrics(ytr, ptr, best["threshold"]),
        "dev": metrics(ydv, pdv, best["threshold"]),
        "test": metrics(yte, pte, best["threshold"]),
    }


def leave_one_opponent_out(rows: list[dict], feature_names: list[str], lam: float, threshold: float):
    opponents = sorted({r["metadata"]["opponent"] for r in rows})
    out = {}
    for held in opponents:
        tr = [r for r in rows if r["metadata"]["opponent"] != held]
        te = [r for r in rows if r["metadata"]["opponent"] == held]
        if not tr or not te:
            continue
        Xtr, ytr = prepare(tr, feature_names)
        Xte, yte = prepare(te, feature_names)
        model = fit_ridge(Xtr, ytr, lam)
        p = predict(model, Xte)
        out[held] = metrics(yte, p, threshold)
    return out


def grouped_conflicts(rows: list[dict]) -> dict:
    by_state_option = defaultdict(list)
    for r in rows:
        by_state_option[(r["state_hash"], r["option_id"])].append(float(r["score_delta"]))

    repeated = {k:v for k,v in by_state_option.items() if len(v) > 1}
    both_signs = 0
    nonzero_variance = 0
    exact_disagreement = 0
    max_group = 0
    examples = []
    for k, vals in repeated.items():
        max_group = max(max_group, len(vals))
        signs = {sign_class(v) for v in vals}
        if 1 in signs and -1 in signs:
            both_signs += 1
            if len(examples) < 12:
                examples.append({
                    "state_hash": k[0],
                    "option_id": k[1],
                    "labels": vals,
                })
        if len(set(vals)) > 1:
            exact_disagreement += 1
        if pstdev(vals) > 1e-12:
            nonzero_variance += 1

    return {
        "groups": len(by_state_option),
        "repeated_groups": len(repeated),
        "max_group_size": max_group,
        "groups_with_exact_label_disagreement": exact_disagreement,
        "groups_with_nonzero_variance": nonzero_variance,
        "groups_with_both_positive_and_negative": both_signs,
        "both_sign_conflict_examples": examples,
    }


def feature_alias_conflicts(rows: list[dict], feature_names: list[str]) -> dict:
    groups = defaultdict(list)
    for r in rows:
        vals = tuple(round(float(r["features"][k]), 12) for k in feature_names)
        key = (r["option_id"], vals)
        groups[key].append(float(r["score_delta"]))

    repeated = {k:v for k,v in groups.items() if len(v) > 1}
    both = sum(
        1 for vals in repeated.values()
        if any(v > 0 for v in vals) and any(v < 0 for v in vals)
    )
    disagree = sum(1 for vals in repeated.values() if len(set(vals)) > 1)
    return {
        "feature_groups": len(groups),
        "repeated_feature_groups": len(repeated),
        "feature_groups_with_label_disagreement": disagree,
        "feature_groups_with_both_positive_and_negative": both,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--input",
        default="runs/option_value_v1_250/TRAINING_ROWS.jsonl",
    )
    ap.add_argument(
        "--out",
        default="runs/option_value_v1_250/SELECTOR_AUDIT_V1.json",
    )
    args = ap.parse_args()

    path = Path(args.input)
    rows = [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    if not rows:
        raise SystemExit("no rows")

    feature_names = list(rows[0]["features"].keys())
    for k in feature_names:
        if any(tok in k.lower() for tok in FORBIDDEN_FEATURE_TOKENS):
            raise SystemExit(f"forbidden model feature: {k}")
    for r in rows:
        if list(r["features"].keys()) != feature_names:
            raise SystemExit("inconsistent feature key order")

    by_option = {
        o: summarize_rows([r for r in rows if r["option_id"] == o])
        for o in sorted({r["option_id"] for r in rows})
    }
    by_opponent = {
        o: summarize_rows([r for r in rows if r["metadata"]["opponent"] == o])
        for o in sorted({r["metadata"]["opponent"] for r in rows})
    }
    by_opponent_option = {}
    for opp in sorted({r["metadata"]["opponent"] for r in rows}):
        by_opponent_option[opp] = {}
        for opt in sorted({r["option_id"] for r in rows}):
            by_opponent_option[opp][opt] = summarize_rows([
                r for r in rows
                if r["metadata"]["opponent"] == opp and r["option_id"] == opt
            ])

    model = train_dev_test(rows, feature_names)
    loo = leave_one_opponent_out(
        rows,
        feature_names,
        float(model["selection"]["lambda"]),
        float(model["selection"]["threshold"]),
    )

    result = {
        "schema": "kculture-option-value-selector-audit-v1",
        "input": str(path),
        "rows": len(rows),
        "unique_state_hashes": len({r["state_hash"] for r in rows}),
        "feature_count": len(feature_names),
        "feature_names": feature_names,
        "by_option": by_option,
        "by_opponent": by_opponent,
        "by_opponent_option": by_opponent_option,
        "state_option_conflicts": grouped_conflicts(rows),
        "feature_alias_conflicts": feature_alias_conflicts(rows, feature_names),
        "grouped_ridge_gate": model,
        "leave_one_opponent_out": loo,
        "automatic_kaggle_submission": False,
    }

    # Gate interpretation: require positive held-out selector delta and not more
    # negative fires than always-fire negative labels in the test set.
    test = result["grouped_ridge_gate"]["test"]
    selector_positive = (test["realized_selector_delta"] or 0.0) > 0.0
    captures = int(test["positive_captures"])
    negfires = int(test["negative_fires"])
    result["decision"] = (
        "OPTION_VALUE_SELECTOR_AUDIT_PASS_LEARNABLE"
        if selector_positive and captures >= 2 and negfires <= max(1, captures // 2)
        else "OPTION_VALUE_SELECTOR_AUDIT_INSUFFICIENT_GENERALIZATION"
    )

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    compact = {
        "decision": result["decision"],
        "rows": result["rows"],
        "unique_state_hashes": result["unique_state_hashes"],
        "state_option_conflicts": result["state_option_conflicts"],
        "feature_alias_conflicts": result["feature_alias_conflicts"],
        "selection": model["selection"],
        "test": model["test"],
        "leave_one_opponent_out": loo,
    }
    print("OPTION_VALUE_SELECTOR_AUDIT", json.dumps(compact, sort_keys=True))


if __name__ == "__main__":
    main()
