"""Closed-loop parity gate: kaggle-environments 1.32.7 vs kagsim 1.32.7.

Unlike a fixed replay test, actions here are generated by the actual submission
packages from the current Kaggle observation. The same action pair is then sent
to both engines. Before every action, agent-visible observations are compared.
Any transition, RNG, observation or reward mismatch therefore fails at the first
turn on an adaptive candidate trajectory.

The kagsim adapter injects observation.step from Game.step_count because the real
Kaggle interpreter exposes step to the agent. No fixed shop/draw tape is used:
normal path-dependent RNG is mandatory for hosted-faithful simulation.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import tempfile
import traceback
from pathlib import Path

import kagsim
from kaggle_environments import make

from kaggle_faithful_h2h import (
    AgentProcess,
    MASTER_SEED,
    PASS,
    extract,
    kagsim_agent_obs,
    make_seeds,
    norm,
)

COMPARE_KEYS = ("player", "day", "hour", "farms", "market", "town", "private", "step")


def diff_path(a, b, path=""):
    if isinstance(a, dict) and isinstance(b, dict):
        for key in sorted(set(a) | set(b)):
            if key not in a:
                return f"{path}.{key} missing in Kaggle"
            if key not in b:
                return f"{path}.{key} missing in kagsim"
            d = diff_path(a[key], b[key], f"{path}.{key}")
            if d:
                return d
        return None
    if isinstance(a, list) and isinstance(b, list):
        if len(a) != len(b):
            return f"{path} length {len(a)} vs {len(b)}"
        for i, (x, y) in enumerate(zip(a, b)):
            d = diff_path(x, y, f"{path}[{i}]")
            if d:
                return d
        return None
    if a != b:
        return f"{path}: Kaggle={a!r} kagsim={b!r}"
    return None


def compare_observation(real_obs, sim_obs):
    real = norm(real_obs)
    sim = norm(sim_obs)
    for key in COMPARE_KEYS:
        if key not in real:
            return f"{key} missing in Kaggle observation"
        if key not in sim:
            return f"{key} missing in adapted kagsim observation"
        d = diff_path(real[key], sim[key], key)
        if d:
            return d
    return None


def status_done(s) -> bool:
    return str(s) in {"DONE", "ERROR", "INVALID", "TIMEOUT"}


def play_parity(a_dir: Path, b_dir: Path, seed: int, a_seat: int) -> dict:
    import multiprocessing as mp

    env = make(
        "kaggriculture",
        configuration={"episodeSteps": 720, "seed": int(seed)},
        debug=False,
    )
    env.reset(2)
    game = kagsim.Game(int(seed))
    config = norm(env.configuration)
    ctx = mp.get_context("spawn")
    a_rng = (int(seed) * 1009 + a_seat * 17 + 1) % 2147483647
    b_rng = (int(seed) * 1013 + a_seat * 19 + 2) % 2147483647
    a = AgentProcess(ctx, a_dir, f"parity_a_{seed}_{a_seat}", a_rng)
    b = AgentProcess(ctx, b_dir, f"parity_b_{seed}_{a_seat}", b_rng)
    action_hash = hashlib.sha256()
    state_hash = hashlib.sha256()
    checked_blocks = 0
    try:
        turn = 0
        while not all(status_done(s.status) for s in env.state):
            if game.done:
                raise RuntimeError(f"kagsim terminated early at turn {turn}")
            real_obs = [norm(env.state[p].observation) for p in (0, 1)]
            sim_obs = [kagsim_agent_obs(game, p) for p in (0, 1)]
            for p in (0, 1):
                d = compare_observation(real_obs[p], sim_obs[p])
                if d:
                    raise AssertionError(f"turn {turn} seat {p}: {d}")
                checked_blocks += len(COMPARE_KEYS)
                state_hash.update(json.dumps(real_obs[p], sort_keys=True, separators=(",", ":")).encode())
            if a_seat == 0:
                x = a.call(real_obs[0], config)
                y = b.call(real_obs[1], config)
            else:
                x = b.call(real_obs[0], config)
                y = a.call(real_obs[1], config)
            pair = [x or PASS, y or PASS]
            action_hash.update(json.dumps(pair, sort_keys=True, separators=(",", ":")).encode())
            env.step(pair)
            game.step(pair[0], pair[1])
            turn += 1
            if turn > 725:
                raise RuntimeError("episode exceeded expected length")

        if not game.done:
            raise AssertionError("Kaggle terminated but kagsim did not")
        real_rewards = [float(env.state[p].reward or 0.0) for p in (0, 1)]
        sim_rewards = [float(game.reward(p)) for p in (0, 1)]
        if real_rewards != sim_rewards:
            raise AssertionError(f"final rewards Kaggle={real_rewards} kagsim={sim_rewards}")
        return {
            "seed": int(seed),
            "a_seat": int(a_seat),
            "turns": turn,
            "checked_field_blocks": checked_blocks,
            "real_rewards": real_rewards,
            "kagsim_rewards": sim_rewards,
            "action_digest": action_hash.hexdigest(),
            "state_digest": state_hash.hexdigest(),
            "status": "PASS",
        }
    finally:
        a.close()
        b.close()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--a", required=True)
    ap.add_argument("--b", required=True)
    ap.add_argument("--a-id", required=True)
    ap.add_argument("--b-id", required=True)
    ap.add_argument("--seed-count", type=int, default=4)
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    from importlib.metadata import version
    kaggle_version = version("kaggle-environments")
    if kaggle_version != "1.32.7":
        raise RuntimeError(f"expected kaggle-environments 1.32.7, got {kaggle_version}")
    if str(getattr(kagsim, "ENGINE_VERSION", "")) != "1.32.7":
        raise RuntimeError(f"expected kagsim engine 1.32.7, got {getattr(kagsim, 'ENGINE_VERSION', None)!r}")

    seeds = make_seeds(args.seed_count, MASTER_SEED)
    rows = []
    errors = []
    with tempfile.TemporaryDirectory(prefix="kculture-parity-") as td:
        root = Path(td)
        a_dir = extract(Path(args.a), root, "agent_a")
        b_dir = extract(Path(args.b), root, "agent_b")
        for seed in seeds:
            for a_seat in (0, 1):
                try:
                    row = play_parity(a_dir, b_dir, seed, a_seat)
                    rows.append(row)
                    print(json.dumps({"seed": seed, "a_seat": a_seat, "status": "PASS", "turns": row["turns"]}), flush=True)
                except Exception as exc:
                    errors.append({
                        "seed": seed,
                        "a_seat": a_seat,
                        "error": repr(exc),
                        "traceback": traceback.format_exc()[-8000:],
                    })
                    print(json.dumps({"seed": seed, "a_seat": a_seat, "status": "FAIL", "error": repr(exc)}), flush=True)
                    break
            if errors:
                break

    # Same environment seed does not promise the same exogenous tape across
    # different action trajectories. This records whether the seat-swapped paths
    # actually diverged; divergence is expected and is not a parity failure.
    path_pairs = {}
    for row in rows:
        path_pairs.setdefault(row["seed"], {})[row["a_seat"]] = row["state_digest"]
    divergent = sum(
        len(v) == 2 and v.get(0) != v.get(1)
        for v in path_pairs.values()
    )
    payload = {
        "schema_version": "kculture-kaggle-parity-v1",
        "reference_backend": "kaggle-environments==1.32.7",
        "accelerator_backend": "kagsim ENGINE_VERSION 1.32.7",
        "kagsim_source_commit": os.environ.get("KAGSIM_SOURCE_COMMIT", "unknown"),
        "simulation_mode": "hosted_faithful_path_dependent_rng",
        "forced_environment_tape": False,
        "kagsim_observation_adapter": "inject step=Game.step_count",
        "a": args.a_id,
        "b": args.b_id,
        "seed_count": args.seed_count,
        "episodes_expected": args.seed_count * 2,
        "episodes_passed": len(rows),
        "seat_swapped_paths_diverged_count": divergent,
        "rows": rows,
        "errors": errors,
        "verdict": "PASS" if not errors and len(rows) == args.seed_count * 2 else "FAIL",
    }
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({k: v for k, v in payload.items() if k != "rows"}, indent=2, sort_keys=True))
    if payload["verdict"] != "PASS":
        raise SystemExit(4)


if __name__ == "__main__":
    main()
